name: Daily KOSDAQ Update

on:
  schedule:
    # 분 시 일 월 요일 (UTC 기준)
    # 한국 시간(KST) 기준 매일 14:00(오후 2시), 20:00(오후 8시) 실행
    - cron: '0 5,11 * * *'
  workflow_dispatch: # 내가 원할 때 수동으로 돌려볼 수 있는 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Scraper
        run: python kosdaq_scraper.py
      - name: Install dependencies
        run: |
          pip install requests pandas lxml openpyxl
      - name: Run script
        run: python your_script_name.py                       
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.xlsx
          git commit -m "Update KOSDAQ Data" || exit 0
          git push
